name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: "Get all changes from github"
        uses: actions/checkout@v2

      - name: Compile latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: verslag.tex
          latexmk_use_lualatex: true
          working_directory: Verslag
        
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: Verslag/verslag.pdf
          
          


